Description: Secondary RDS template

Parameters:
  VpcStackName:
    Description: Name of the VPC stack to retrieve subnet configurations
    Type: String
  DBInstanceIdentifier:
    Description: RDS DB instance name
    Type: String
  PrimaryRDSIdentifier: 
    Description: ARN identifier for the main RDS
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "subnet"
      SubnetIds: 
        Fn::Split:
          - ","
          - Fn::ImportValue: !Sub "${VpcStackName}-PrivateSubnets"
  MySQL:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${VpcStackName}-DatabaseSecurityGroup"
      DBSubnetGroupName: !Ref DBSubnetGroup
      SourceDBInstanceIdentifier: !Sub ${PrimaryRDSIdentifier}
      DBInstanceIdentifier: !Sub ${DBInstanceIdentifier}
      AllocatedStorage: 5
      DBInstanceClass: db.t2.small
      Engine: MySQL

Outputs:
  SubnetGroup:
    Description: Subnet group id
    Value: !Ref DBSubnetGroup
